In [5]:
import torch

In [6]:
# 1.1 Создание тензоров
# Создайте следующие тензоры:
# - Тензор размером 3x4, заполненный случайными числами от 0 до 1
# - Тензор размером 2x3x4, заполненный нулями
# - Тензор размером 5x5, заполненный единицами
# - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)

# - Тензор размером 3x4, заполненный случайными числами от 0 до 1
random_tensor = torch.rand(3, 4)
print(random_tensor)

# - Тензор размером 2x3x4, заполненный нулями
zeros_tensor = torch.rand(2, 3, 4)
print(zeros_tensor)

# - Тензор размером 5x5, заполненный единицами
ones_tensor = torch.ones(5, 5)
print(ones_tensor)
# - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)
# Сначала создаем одномерный тензор с числами от 0 до 15
range_tensor_flat = torch.arange(16)
# Затем изменяем его форму на 4x4
reshape_tensor = range_tensor_flat.reshape(4, 4)
print(reshape_tensor)

tensor([[0.6440, 0.9760, 0.4735, 0.1726],
        [0.2055, 0.8152, 0.7495, 0.8852],
        [0.0329, 0.6949, 0.9122, 0.5553]])
tensor([[[0.3146, 0.8283, 0.1271, 0.9956],
         [0.1100, 0.6865, 0.8513, 0.4633],
         [0.4566, 0.5958, 0.4899, 0.3472]],

        [[0.0358, 0.4438, 0.2147, 0.6047],
         [0.6364, 0.0820, 0.4867, 0.2500],
         [0.3155, 0.6613, 0.3793, 0.5667]]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [7]:
# 1.2 Операции с тензорами
# Дано: тензор A размером 3x4 и тензор B размером 4x3
# Выполните:
# - Транспонирование тензора A
# - Матричное умножение A и B
# - Поэлементное умножение A и транспонированного B
# - Вычислите сумму всех элементов тензора


A = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
], dtype=torch.float32)

B = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
], dtype=torch.float32)

print(A, "\n", B)

A_T = A.T

print(A_T)

C = torch.matmul(A, B)
print(C)

B_T = B.T
elementwise_product = torch.mul(A, B_T)
print(elementwise_product)

sum_A = A.sum()
print(sum_A)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]) 
 tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.],
        [ 4.,  8., 12.]])
tensor([[ 70.,  80.,  90.],
        [158., 184., 210.],
        [246., 288., 330.]])
tensor([[  1.,   8.,  21.,  40.],
        [ 10.,  30.,  56.,  88.],
        [ 27.,  60.,  99., 144.]])
tensor(78.)


In [10]:
#1.3 Индексация и срезы
# Создайте тензор размером 5x5x5
# Извлеките:
# - Первую строку
# - Последний столбец
# - Подматрицу размером 2x2 из центра тензора
# - Все элементы с четными индексами

# Создаем тензор 5x5x5, заполненный числами от 0 до 124
# Сначала создадим одномерный тензор, а затем изменим его форму
tensor_3d = torch.arange(125).reshape(5, 5, 5)
print(tensor_3d)

# Извлечение первой строки из каждой плоскости (по первому измерению)
first_row_across_planes = tensor_3d[:, 0, :]
print(first_row_across_planes)

# Извлечение последнего столбца из каждой плоскости (по первому измерению)
last_column_across_planes = tensor_3d[:, :, -1]
print(last_column_across_planes)

# Центральный "слайс" находится по индексу 2
# Центральные строки/столбцы: индексы 1:3 для подматрицы 2x2 из центра 5x5
# (Индексы 2 и 3 для 5x5 матрицы будут 2:4)
# Для 2x2 из 5x5: начало с индекса 1 и до индекса 3 (не включая)
center_submatrix = tensor_3d[2, 1:3, 1:3]
print(center_submatrix)

# Извлечение всех элементов с четными индексами по всем измерениям
even_indexed_elements = tensor_3d[::2, ::2, ::2]
print(even_indexed_elements)



tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24]],

        [[ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74]],

        [[ 75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124]]])
tensor([[  0,   1,   2,   3,   4],
        [ 25,  26,  27,  28,  29],
        [ 50,  51,  

In [11]:
# Создайте тензор размером 24 элемента
# Преобразуйте его в формы:
# - 2x12
# - 3x8
# - 4x6
# - 2x3x4
# - 2x2x2x3

# Создаем одномерный тензор из 24 элементов
# Заполним его числами от 0 до 23 для наглядности
original_tensor = torch.arange(24)
print(original_tensor)

# Преобразование в форму 2x12
reshaped_2x12 = original_tensor.reshape(2, 12)
print(reshaped_2x12)

# Преобразование в форму 3x8
reshaped_3x8 = original_tensor.reshape(3, 8)
print(reshaped_3x8)

# Преобразование в форму 4x6
reshaped_4x6 = original_tensor.reshape(4, 6)
print(reshaped_4x6)

# Преобразование в форму 2x3x4
reshaped_2x3x4 = original_tensor.reshape(2, 3, 4)
print(reshaped_2x3x4)

# Преобразование в форму 2x2x2x3
reshaped_2x2x2x3 = original_tensor.reshape(2, 2, 2, 3)
print(reshaped_2x2x2x3)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]])
